[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "production"
  VITE_APP_NAME = "HISL Control"
  VITE_DEEPSEEK_API_KEY = "sk-3bfecdbb798e441e82899dfabfd39ec6"

[context.production]
  command = "npm install --legacy-peer-deps && npm run build"

[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build"

[context.branch-deploy]
  command = "npm install --legacy-peer-deps && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

